Repository tsparticles/404-templates, pull requests merged in 2023-10, with the labels that each got.

#112 build: removed Node 14.x support
  .github/workflows/node.js.yml
Labels: size/XS

#113 Add Jitter template
  __screenshots/jitter.png
  data/pages.json
  jitter/404.html
  jitter/app.js
  jitter/styles.css
Labels: size/XL

#115 Fixed some script urls
  autumn/404.html
  matrix/404.html
  ocean/404.html
Labels: size/XS

#116 added new 404 template with party theme
  __screenshots/party.png
  data/pages.json
  party/404.html
  party/images/Dance-1.gif
  party/images/Dance-2.gif
  party/images/Dance-3.gif
  party/images/Dance-4.gif
  party/script.js
  party/style.css
Labels: size/L

#120 Corrected URL in pages.json
  data/pages.json
Labels: size/XS

#121 Add Glitch 404 page
  __screenshots/glitch.png
  data/pages.json
  glitch/404.html
  glitch/css/404.css
  glitch/js/404.js
Labels: size/L

#126 Added ESLint for better checks
  .eslintrc.js
  .github/workflows/node.js.yml
  .prettierignore
  .prettierrc
  dots/js/animate.js
  imposter/js/404.js
  jitter/app.js
  js/main.js
  links/js/404.js
  package-lock.json
  package.json
  playful/js/404.js
  pole/js/404.js
  space/js/404.js
  spooky/js/404.js
  traveller/js/404.js
Labels: size/L
